defmodule NervesViewWeb.ClipPlayerLive do
  @moduledoc """
  Inline HLS player for a single recorded clip. Loads the m3u8 generated by
  `RecordingController.playlist/2` and plays it via hls.js. Used when the
  user clicks "Open" on a row in the Recordings page.

  A "Download" button in the card footer serves a concatenated stream of the
  clip's TS segments so the user can save the footage locally.
  """

  use NervesViewWeb, :live_view

  import NervesViewWeb.Helpers

  alias NervesView.DVR.SegmentIndex

  @impl true
  def mount(%{"id" => clip_id}, _session, socket) do
    case SegmentIndex.get_clip(clip_id) do
      {:ok, clip} ->
        {:ok,
         socket
         |> assign(page_title: "Recording · #{format_ts(clip.started_at, 0)}")
         |> assign(clip: clip)
         |> assign(playlist_url: ~p"/recordings/#{clip.id}/playlist.m3u8")
         |> assign(tz_offset: 0)}

      {:error, _} ->
        {:ok,
         socket
         |> put_flash(:error, "Recording not found.")
         |> redirect(to: ~p"/recordings")}
    end
  end

  @impl true
  def handle_event("tz:offset", %{"offset_minutes" => offset}, socket) do
    off = String.to_integer(offset)
    {:noreply, assign(socket, tz_offset: off)}
  end

  @impl true
  def render(assigns) do
    ~H"""
    <div>
      <div class="flex items-center gap-3 mb-4">
        <.button variant="ghost" size="sm" navigate={~p"/recordings"}>
          &larr; All recordings
        </.button>
        <div>
          <h1 class="pg-title">{format_ts(@clip.started_at, @tz_offset)}</h1>
          <p class="pg-sub">
            {@clip.camera_id} · {format_duration(@clip.started_at, @clip.ended_at)}
            · {format_bytes(@clip.size_bytes)} · {length(@clip.segments)} segments
          </p>
        </div>
      </div>

      <.card class="overflow-hidden">
        <:content class="p-0">
          <div class="cam-vp cam-vp-full">
            <video
              id={"clip-player-#{@clip.id}"}
              class="cam-vid"
              controls
              autoplay
              playsinline
              phx-hook="ClipPlayer"
              data-src={@playlist_url}
            />
          </div>
        </:content>
        <:footer>
          <div class="flex items-center justify-between px-1">
            <span class="text-xs text-muted-foreground">
              {format_ts(@clip.started_at, @tz_offset)} &mdash; {format_ts(@clip.ended_at, @tz_offset)}
            </span>
            <a
              href={~p"/recordings/#{@clip.id}/download"}
              class="inline-flex items-center gap-1.5 text-xs font-medium text-primary hover:underline"
              download
            >
              <svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" d="M3 16.5v2.25A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75V16.5M16.5 12 12 16.5m0 0L7.5 12m4.5 4.5V3" />
              </svg>
              Download
            </a>
          </div>
        </:footer>
      </.card>
    </div>
    """
  end

  defp format_ts(unix, tz_offset) when is_integer(unix) do
    fmt_ts_local(unix, tz_offset, "%b %d, %Y · %H:%M:%S")
  end

  defp format_ts(_, _tz_offset), do: "—"

  defp format_bytes(bytes) when bytes < 1024, do: "#{bytes} B"
  defp format_bytes(bytes) when bytes < 1_048_576, do: "#{Float.round(bytes / 1024, 1)} KB"
  defp format_bytes(bytes) when bytes < 1_073_741_824, do: "#{Float.round(bytes / 1_048_576, 1)} MB"
  defp format_bytes(bytes), do: "#{Float.round(bytes / 1_073_741_824, 1)} GB"

  defp format_duration(started, ended) when is_integer(started) and is_integer(ended) do
    secs = max(ended - started, 0)

    cond do
      secs < 60 -> "#{secs}s"
      secs < 3600 -> "#{div(secs, 60)}m #{rem(secs, 60)}s"
      true -> "#{div(secs, 3600)}h #{div(rem(secs, 3600), 60)}m"
    end
  end

  defp format_duration(_, _), do: "—"
end
