defmodule NervesViewWeb.ClipPlayerLive do
  @moduledoc """
  Inline HLS player for a single recorded clip. Loads the m3u8 generated by
  `RecordingController.playlist/2` and plays it via hls.js. Used when the
  user clicks "Open" on a row in the Recordings page.
  """

  use NervesViewWeb, :live_view

  alias NervesView.DVR.SegmentIndex

  @impl true
  def mount(%{"id" => clip_id}, _session, socket) do
    case SegmentIndex.get_clip(clip_id) do
      {:ok, clip} ->
        {:ok,
         socket
         |> assign(page_title: "Recording · #{format_ts(clip.started_at)}")
         |> assign(clip: clip)
         |> assign(playlist_url: ~p"/recordings/#{clip.id}/playlist.m3u8")}

      {:error, _} ->
        {:ok,
         socket
         |> put_flash(:error, "Recording not found.")
         |> redirect(to: ~p"/recordings")}
    end
  end

  @impl true
  def render(assigns) do
    ~H"""
    <div>
      <div class="flex items-center gap-3 mb-4">
        <.button variant="ghost" size="sm" navigate={~p"/recordings"}>
          ← All recordings
        </.button>
        <div>
          <h1 class="pg-title">{format_ts(@clip.started_at)}</h1>
          <p class="pg-sub">
            {@clip.camera_id} · {format_duration(@clip.started_at, @clip.ended_at)}
            · {format_bytes(@clip.size_bytes)} · {length(@clip.segments)} segments
          </p>
        </div>
      </div>

      <.card class="overflow-hidden">
        <:content class="p-0">
          <div class="cam-vp cam-vp-full">
            <video
              id={"clip-player-#{@clip.id}"}
              class="cam-vid"
              controls
              autoplay
              playsinline
              phx-hook="ClipPlayer"
              data-src={@playlist_url}
            />
          </div>
        </:content>
      </.card>
    </div>
    """
  end

  # ── Formatting ─────────────────────────────────────────────────────────

  defp format_ts(unix) when is_integer(unix) do
    case DateTime.from_unix(unix) do
      {:ok, dt} -> Calendar.strftime(dt, "%b %d, %Y · %H:%M:%S")
      _ -> "—"
    end
  end

  defp format_ts(_), do: "—"

  defp format_bytes(bytes) when bytes < 1024, do: "#{bytes} B"
  defp format_bytes(bytes) when bytes < 1_048_576, do: "#{Float.round(bytes / 1024, 1)} KB"
  defp format_bytes(bytes) when bytes < 1_073_741_824, do: "#{Float.round(bytes / 1_048_576, 1)} MB"
  defp format_bytes(bytes), do: "#{Float.round(bytes / 1_073_741_824, 1)} GB"

  defp format_duration(started, ended) when is_integer(started) and is_integer(ended) do
    secs = max(ended - started, 0)

    cond do
      secs < 60 -> "#{secs}s"
      secs < 3600 -> "#{div(secs, 60)}m #{rem(secs, 60)}s"
      true -> "#{div(secs, 3600)}h #{div(rem(secs, 3600), 60)}m"
    end
  end

  defp format_duration(_, _), do: "—"
end
